services:
  chatapp-1:
    image: dhani/chatapp-main:1.0-SNAPSHOT
    ports:
      - 8092:8090
    environment:
      QUARKUS_APPLICATION_NAME: chatapp-1
      KAFKA_GROUP_ID: chatapp-1
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres:5432/quarkus_test
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_test
      QUARKUS_FLYWAY_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_test
    deploy:
      replicas: 0
  chatapp:
    image: dhani/chatapp-main:1.0-SNAPSHOT
    ports:
      - 8091:8090
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092
      QUARKUS_APPLICATION_NAME: chatapp-0
      KAFKA_GROUP_ID: chatapp-0
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgres:5432/quarkus_test
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_test
      QUARKUS_FLYWAY_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_test
    deploy:
      replicas: 0
  kafka-1:
    image: apache/kafka:latest
    container_name: kafka-1
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    deploy:
      resources:
        limits:
          memory: 384m
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - 8081:8080
    environment:
      KAFKA_BROKERS: kafka-1:9092
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test